Added check to prevent loading the rel loader file twice, added butto…
SeekyCt/spm-practice-codes pull request #58
Opened 2023-07-30 16:15 UTC by JohnP55

…n to get all characters and pixls, added on selection handler for buttons, made rel2bin.py generate bins in the out folder

2023-07-31 17:55 UTC, SeekyCt requested changes

2023-07-31 17:55 UTC, SeekyCt commented on spm-headers/include/spm/seq_load.h
> +typedef struct {
The additions to this file should be in a new seq_load_sub header instead

2023-07-31 17:55 UTC, SeekyCt commented on spm-headers/include/spm/seq_load.h
> +DECOMP_STATIC(SeqLoadWork* seqLoadWp)
In spm-headers the convention for static symbols is a snake case filename prefix and then symbol name (like `seq_load_sub_wp`

2023-07-31 17:55 UTC, SeekyCt commented on spm-headers/include/spm/seq_load.h
> +s32 seq_load_sub_loadMain(); // from seq_load_sub
The prefix here isn't needed since this isn't a static symbol

2023-07-31 17:55 UTC, SeekyCt commented on source/inventorymenu.cpp
> +    ModeDef chars = modes[3];
Slightly more efficient to take const references to the mode defs, this would create copies of the whole def on the stack

2023-07-31 17:55 UTC, SeekyCt commented on include/inventorymenu.h
> +    const char * mAllCharsPixlsMsg;
The class fields are grouped by what screen they're used on, these fields would go in the slot selection screen section

2023-07-31 17:55 UTC, SeekyCt commented on include/mod.h
> +extern int relLoaderTwiceEvtId;
The rel loader stuff should probably go in a new file (same for the cpp side)

2023-09-18 22:49 UTC, JohnP55 commented
Fixes #54 and #55

2023-09-18 23:11 UTC, SeekyCt approved these changes

2023-09-18 23:11 UTC, SeekyCt commented
Looks good, thanks :)

2023-09-18 23:12 UTC, merged